# Generated by Django 4.1.6 on 2023-03-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('course', '0012_rate_interaction_comment'),
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_grade', to='course.grade'),
        ),
        migrations.AddField(
            model_name='tempstudent',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_student_grade', to='course.grade'),
        ),
    ]
