# Generated by Django 4.1.6 on 2023-09-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
