# Generated by Django 4.1.6 on 2023-10-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='waiter',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
