# Generated by Django 4.1.6 on 2023-11-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_waiter_created_waiter_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiter',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
