# Generated by Django 4.1.6 on 2023-04-27 09:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0031_video_grade_video_lesson_video_subject_video_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Android In-App', max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('purchase_token', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('expires_date', models.DateTimeField(db_index=True, default=datetime.datetime.now, null=True)),
                ('purchase_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('subscription_Id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('purchaseState', models.SmallIntegerField(default=1)),
                ('acknowledgementState', models.SmallIntegerField(default=0)),
                ('consumptionState', models.SmallIntegerField(default=0)),
                ('paymentState', models.SmallIntegerField(default=0)),
                ('country_code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('regionCode', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('currency', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppleNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Apple In-App', max_length=255, null=True)),
                ('environment', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('original_transaction_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('original_purchase_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('product_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('auto_renew_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('expiration_intent', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('in_app_ownership_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('symbol', models.CharField(default=True, max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InAppPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('environment', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('original_transaction_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('expires_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('original_purchase_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('auto_renew_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('expiration_intent', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('in_app_ownership_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('product_id', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('currency', models.CharField(blank=True, default='=N=', max_length=15, null=True)),
                ('duration', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('platform', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_products', to='subscribe.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_grade', to='course.grade')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_method_subscriptions', to='subscribe.inapppayment')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_subscribers', to='subscribe.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(default='', max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('interval', models.CharField(default='', max_length=100, null=True)),
                ('amount', models.CharField(default='', max_length=100, null=True)),
                ('currency', models.CharField(default='=N=', max_length=15, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('duration', models.SmallIntegerField(default=0)),
                ('status', models.BooleanField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_plans', to='subscribe.discount')),
            ],
        ),
        migrations.AddField(
            model_name='inapppayment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='subscribe.product'),
        ),
    ]
