# Generated by Django 4.1.6 on 2023-03-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='grade',
        ),
    ]
