# Generated by Django 4.1.6 on 2023-03-01 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_video_grade_alter_video_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='discount',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='subscribe.discount'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='grade',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_grade', to='course.grade'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='plan',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='subscribe.plan'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
