# Generated by Django 4.1.6 on 2023-03-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_alter_plan_discount_alter_subscribe_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
