# Generated by Django 4.1.6 on 2023-03-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
