# Generated by Django 4.1.6 on 2023-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_subscribe_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('grades', models.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='grade',
        ),
    ]
