# Generated by Django 4.1.6 on 2023-03-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_subscribe_grade'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='subscribe',
    #         name='payment',
    #     ),
    # ]
