# Generated by Django 4.1.6 on 2023-03-01 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_alter_plan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='expiry_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 3, 1, 10, 26, 32, 714197), null=True),
        ),
    ]
