# Generated by Django 4.1.6 on 2023-05-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_subscribe_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradepack',
            name='range',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
