# Generated by Django 4.1.6 on 2023-04-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_inapppayment_subscribe_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='payment',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_method_subscriptions', to='subscribe.inapppayment'),
        ),
        migrations.AlterField(
            model_name='inapppayment',
            name='auto_renew_status',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inapppayment',
            name='environment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inapppayment',
            name='expiration_intent',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inapppayment',
            name='expires_date',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inapppayment',
            name='in_app_ownership_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inapppayment',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inapppayment',
            name='original_transaction_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inapppayment',
            name='original_transaction_id2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inapppayment',
            name='posix_date_time',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inapppayment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='subscribe.product'),
        ),
        migrations.AlterField(
            model_name='inapppayment',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
