# Generated by Django 4.1.6 on 2023-03-01 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_subscribe_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='expiry_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
