# Generated by Django 4.1.6 on 2023-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_gradepack_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradepack',
            name='name',
        ),
        migrations.AddField(
            model_name='gradepack',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gradepack',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
