# Generated by Django 4.1.6 on 2023-03-01 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_alter_subscribe_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='expiry_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, null=True),
        ),
    ]
