# Generated by Django 4.1.6 on 2023-04-04 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_remove_subscribe_payment_subscribe_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inapppayment',
            name='original_transaction_id2',
        ),
        migrations.RemoveField(
            model_name='inapppayment',
            name='posix_date_time',
        ),
        migrations.AddField(
            model_name='inapppayment',
            name='original_purchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
