# Generated by Django 4.1.6 on 2023-03-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0007_alter_subscribe_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='expiry_date',
        ),
    ]
