# Generated by Django 4.1.6 on 2023-05-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0007_remove_gradepack_name_gradepack_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradepack',
            name='range',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
