# Generated by Django 4.1.6 on 2023-04-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0008_remove_subscribe_plan_product_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_subscribers', to='subscribe.product'),
        ),
    ]
