# Generated by Django 4.1.6 on 2023-05-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0008_alter_gradepack_range'),
    ]

    operations = [
    ]
