# Generated by Django 4.1.6 on 2023-05-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0009_auto_20230527_1210'),
    ]

    operations = [
    ]
