# Generated by Django 4.1.6 on 2023-04-04 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribe', '0011_alter_subscribe_product_alter_subscribe_user'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='inapppayment',
        #     name='product',
        # ),
        migrations.RemoveField(
            model_name='subscribe',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_products', to='subscribe.discount'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
