# Generated by Django 4.1.6 on 2023-05-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0011_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
