# Generated by Django 4.1.6 on 2023-04-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0012_remove_inapppayment_product_remove_subscribe_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
