# Generated by Django 4.1.6 on 2023-04-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0013_remove_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
