# Generated by Django 4.1.6 on 2023-05-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0013_plan_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plan_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
