# Generated by Django 4.1.6 on 2023-04-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0014_remove_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='created',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='updated',
        ),
    ]
