# Generated by Django 4.1.6 on 2023-04-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0015_remove_subscribe_created_remove_subscribe_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='created',
        # ),
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='product',
            name='platform',
        ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='updated',
        # ),
    ]
