# Generated by Django 4.1.6 on 2023-04-04 17:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_alter_video_title'),
        ('subscribe', '0016_remove_product_amount_remove_product_created_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='inapppayment',
        #     name='product',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='subscribe.product'),
        # ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        # migrations.AddField(
        #     model_name='product',
        #     name='created',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, default='=N=', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_products', to='subscribe.discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        # migrations.AddField(
        #     model_name='product',
        #     name='updated',
        #     field=models.DateTimeField(auto_now=True),
        # ),
        # migrations.AddField(
        #     model_name='subscribe',
        #     name='created',
        #     field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='subscribe',
        #     name='grade',
        #     field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_grade', to='course.grade'),
        # ),
        # migrations.AddField(
        #     model_name='subscribe',
        #     name='payment_method',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_method_subscriptions', to='subscribe.inapppayment'),
        # ),
        migrations.AddField(
            model_name='subscribe',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_subscribers', to='subscribe.product'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
