# Generated by Django 4.1.6 on 2023-04-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0017_inapppayment_product_product_amount_product_created_and_more'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='product',
    #         name='created',
    #     ),
    # ]
