# Generated by Django 4.1.6 on 2023-04-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0019_remove_inapppayment_product_remove_subscribe_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('product_id', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(blank=True, default='=N=', max_length=15, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('duration', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('platform', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_products', to='subscribe.discount')),
            ],
        ),
    ]
