# Generated by Django 4.1.6 on 2023-04-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0021_inapppayment_product_subscribe_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inapppayment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='product',
        ),
    ]
