# Generated by Django 4.1.6 on 2023-04-04 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0022_remove_inapppayment_product_remove_subscribe_product'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='inapppayment',
        #     name='product',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='subscribe.product'),
        # ),
        migrations.AddField(
            model_name='subscribe',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_subscribers', to='subscribe.product'),
        ),
    ]
