# Generated by Django 4.1.6 on 2023-04-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0023_inapppayment_product_subscribe_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='plans', to='subscribe.plan'),
        ),
    ]
