# Generated by Django 4.1.6 on 2023-04-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0024_subscribe_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='plan',
        ),
    ]
