# Generated by Django 4.1.6 on 2023-04-08 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0025_remove_subscribe_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Apple In-App', max_length=255, null=True)),
                ('environment', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('original_transaction_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('expires_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('original_purchase_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('product_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('auto_renew_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('expiration_intent', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('in_app_ownership_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
