# Generated by Django 4.1.6 on 2023-04-09 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0026_applenotify'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='applenotify',
    #         name='expires_date',
    #         field=models.DateTimeField(db_index=True, default=datetime.datetime.now, null=True),
    #     ),
    # ]
