# Generated by Django 4.1.6 on 2023-04-21 09:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_video_grade_video_lesson_video_subject_video_topic'),
        ('subscribe', '0030_subscribe_created_subscribe_grade_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='subscribe',
        #     name='created',
        #     field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='subscribe',
        #     name='grade',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_grade', to='course.grade'),
        # ),
        # migrations.AlterField(
        #     model_name='applenotify',
        #     name='expires_date',
        #     field=models.DateTimeField(db_index=True, default=datetime.datetime.now, null=True),
        # ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        # migrations.CreateModel(
        #     name='InAppPayment',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
        #         ('environment', models.CharField(blank=True, default='', max_length=255, null=True)),
        #         ('original_transaction_id', models.CharField(blank=True, default='', max_length=255, null=True)),
        #         ('transaction_id', models.CharField(blank=True, default='', max_length=255, null=True)),
        #         ('expires_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
        #         ('original_purchase_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
        #         ('auto_renew_status', models.CharField(blank=True, default='', max_length=255, null=True)),
        #         ('expiration_intent', models.CharField(blank=True, default='', max_length=255, null=True)),
        #         ('in_app_ownership_type', models.CharField(blank=True, default='', max_length=255, null=True)),
        #         ('created', models.DateTimeField(auto_now_add=True)),
        #         ('updated', models.DateTimeField(auto_now=True)),
        #         ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='subscribe.product')),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='subscribe',
        #     name='payment_method',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_method_subscriptions', to='subscribe.inapppayment'),
        # ),
    ]
