version: '3'

services:
    # db:
    #   image: postgres
    #   environment:
    #     POSTGRES_DB: ${DB_NAME}
    #     POSTGRES_USER: ${DB_USER}
    #     POSTGRES_PASSWORD: ${DB_PASSWORD}

    web:
      build: .
      volumes:
          - .:/usr/src/app

      ports:
          - "8000:8000"

      # depends_on:
      #     - db