# Generated by Django 4.1.6 on 2023-03-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='subject',
        #     name='grade',
        #     field=models.ManyToManyField(related_name='grade_subjects', to='course.grade'),
        # ),
    ]
