# Generated by Django 4.1.6 on 2023-03-29 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_subject_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(db_index=True, default='', max_length=255, null=True)),
                ('created', models.DateField(auto_now_add=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('grade', models.ManyToManyField(related_name='grade_topics', to='course.grade')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_topics', to='course.subject')),
            ],
        ),
    ]
