# Generated by Django 4.1.6 on 2023-02-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_comment_video_rate_video_subject_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
