# Generated by Django 4.1.6 on 2023-02-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_subject_created_alter_subject_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='subject',
            field=models.ManyToManyField(default='', null=True, related_name='lecturer_subjects', to='course.subject'),
        ),
    ]
