# Generated by Django 4.1.6 on 2023-03-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_video_grade_video_lesson_video_subject_video_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='updated',
        ),
    ]
