# Generated by Django 4.1.6 on 2023-03-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_topic_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='created',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
    ]
