# Generated by Django 4.1.6 on 2023-02-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_lecturer_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='subject',
            field=models.ManyToManyField(related_name='lecturer_subjects', to='course.subject'),
        ),
    ]
