# Generated by Django 4.1.6 on 2023-03-29 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_topic_created_remove_topic_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='grade',
            field=models.ManyToManyField(related_name='grade_topics', to='course.grade'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_topics', to='course.subject'),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
