# Generated by Django 4.1.6 on 2023-02-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
    ]
