# Generated by Django 4.1.6 on 2023-03-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_topic_created_topic_grade_topic_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='num',
            new_name='chapter',
        ),
    ]
