# Generated by Django 4.1.6 on 2023-03-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_num_topic_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
