# Generated by Django 4.1.6 on 2023-03-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_lesson_title'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='video',
    #         name='grade',
    #     ),
    # ]
