# Generated by Django 4.1.6 on 2023-02-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_discount_plan_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='interactiontype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='lesson',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='topic',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
