# Generated by Django 4.1.6 on 2023-03-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_video_grade'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='video',
    #         name='grade',
    #         field=models.ManyToManyField(default=[], related_name='grade_videos', to='course.grade'),
    #     ),
    # ]
