# Generated by Django 4.1.6 on 2023-02-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_plan_discount_remove_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
