# Generated by Django 4.1.6 on 2023-02-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='aspect_ratio',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
