# Generated by Django 4.1.6 on 2023-04-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_video_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='topics',
            field=models.CharField(choices=[], default=[], max_length=255),
        ),
    ]
