# Generated by Django 4.1.6 on 2023-02-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_resolution_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='media',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
