# Generated by Django 4.1.6 on 2023-04-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_lesson_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='topics',
            field=models.CharField(choices=[], default=[], max_length=255, null=True),
        ),
    ]
