# Generated by Django 4.1.6 on 2023-04-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_lesson_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='topics',
            field=models.CharField(choices=[], default=[], max_length=255, null=True),
        ),
    ]
