# Generated by Django 4.1.6 on 2023-02-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_resolution_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions', to='course.resolution'),
        ),
    ]
