# Generated by Django 4.1.6 on 2023-04-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_video_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='lessons',
            field=models.CharField(choices=[], default=[], max_length=255, null=True),
        ),
    ]
