# Generated by Django 4.1.6 on 2023-02-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_video_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='grade',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='course.grade'),
        ),
        migrations.AlterField(
            model_name='video',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='course.subject'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.TextField(blank=True, default=dict, null=True),
        ),
    ]
