# Generated by Django 4.1.6 on 2023-03-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_video_grade_alter_video_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
