# Generated by Django 4.1.6 on 2023-03-15 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0018_remove_test_grade_remove_test_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='video_time_of_interaction',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='seek_fwd',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='seek_prev',
        ),
        migrations.AddField(
            model_name='video',
            name='end_start_credits',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='start_end_credits',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(db_index=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Seek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(default='', max_length=10, null=True)),
                ('to_duration', models.CharField(default='', max_length=50, null=True)),
                ('from_duration', models.CharField(default='', max_length=50, null=True)),
                ('created', models.DateField(auto_now_add=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeks', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_seeks', to='course.video')),
            ],
        ),
    ]
