# Generated by Django 4.1.6 on 2023-04-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_alter_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
