# Generated by Django 4.1.6 on 2023-04-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_video_grade_video_lesson_video_subject_video_topic_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='lesson',
        #     name='title',
        #     field=models.CharField(db_index=True, max_length=255, unique=True),
        # ),
    ]
