# Generated by Django 4.1.6 on 2023-06-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_video_grade_video_lesson_video_subject_video_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=127)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_interaction', to='course.interactiontype'),
        ),
    ]
