# Generated by Django 4.1.6 on 2023-06-06 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_interactiontype_alter_interaction_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InteractionType',
            new_name='Event',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='type',
        ),
        migrations.AddField(
            model_name='interaction',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='course.event'),
        ),
    ]
