# Generated by Django 4.1.6 on 2023-06-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_rename_interactiontype_event_remove_interaction_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='duration',
            new_name='begin_duration',
        ),
        migrations.AddField(
            model_name='interaction',
            name='end_duration',
            field=models.CharField(db_index=True, default='', max_length=50, null=True),
        ),
    ]
