# Generated by Django 4.1.6 on 2023-06-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_rename_duration_interaction_begin_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='begin_duration',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='end_duration',
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default='000', max_length=255),
        ),
    ]
