# Generated by Django 4.1.6 on 2023-06-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_remove_interaction_begin_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='begin_duration',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='interaction',
            name='end_duration',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
