# Generated by Django 4.1.6 on 2023-06-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0036_interaction_begin_duration_interaction_end_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='end_duration',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True),
        ),
    ]
