# Generated by Django 4.1.6 on 2023-06-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0037_alter_interaction_end_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='begin_duration',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='end_duration',
        ),
    ]
