# Generated by Django 4.1.6 on 2023-06-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0038_remove_interaction_begin_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='begin_duration',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='end_duration',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
