# Generated by Django 4.1.6 on 2023-06-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0040_alter_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
