# Generated by Django 4.1.6 on 2023-06-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0041_alter_lesson_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='title',
        ),
    ]
