# Generated by Django 4.1.6 on 2023-06-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0042_remove_lesson_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
