# Generated by Django 4.1.6 on 2023-06-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0043_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
