# Generated by Django 4.1.6 on 2023-07-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0045_alter_rate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
