# Generated by Django 4.1.6 on 2023-07-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0046_alter_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='topics',
            field=models.CharField(blank=True, choices=[], default=[], max_length=255, null=True),
        ),
    ]
