# Generated by Django 4.1.6 on 2023-07-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0051_alter_interaction_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='course.video'),
        ),
    ]
