# Generated by Django 4.1.6 on 2023-08-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0052_alter_interaction_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_videos', to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lessons',
            field=models.CharField(blank=True, choices=[], default=[], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='topics',
            field=models.CharField(blank=True, choices=[], default=[], max_length=255, null=True),
        ),
    ]
