# Generated by Django 4.1.6 on 2023-08-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0053_alter_video_lesson_alter_video_lessons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='grade',
            field=models.ManyToManyField(default=list, related_name='grade_videos', to='course.grade'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lessons',
            field=models.CharField(blank=True, choices=[], default=list, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='topics',
            field=models.CharField(blank=True, choices=[], default=list, max_length=255, null=True),
        ),
    ]
