# Generated by Django 4.1.6 on 2023-08-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0054_alter_video_grade_alter_video_lessons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions', to='course.resolution'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
