# Generated by Django 4.1.6 on 2023-08-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0055_alter_video_resolution_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url2',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
