# Generated by Django 4.1.6 on 2023-08-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0056_video_url2'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subject',
            name='thumbnail',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
