# Generated by Django 4.1.6 on 2023-10-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0057_subject_color_subject_thumbnail'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='lesson',
    #         name='thumbnail',
    #         field=models.URLField(blank=True, null=True),
    #     ),
    #     migrations.AddField(
    #         model_name='subject',
    #         name='is_active',
    #         field=models.BinaryField(default=True),
    #     ),
    # ]
