# Generated by Django 4.1.6 on 2023-11-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0060_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='urls',
        ),
    ]
