# Generated by Django 4.1.6 on 2023-11-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0062_delete_thumbnailurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
