# Generated by Django 4.1.6 on 2023-11-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0063_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='num',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='url',
            field=models.URLField(blank=True, db_index=True, default='', null=True),
        ),
    ]
