# Generated by Django 4.1.6 on 2023-11-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0064_subject_num_alter_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='image_type',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
