# Generated by Django 4.1.6 on 2023-11-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0065_thumbnail_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image_type',
            field=models.CharField(default='png', max_length=50, null=True),
        ),
    ]
