# Generated by Django 4.1.6 on 2023-11-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0066_alter_thumbnail_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='image_type',
        ),
    ]
