# Generated by Django 4.1.6 on 2023-11-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0068_thumbnail_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(db_index=True, default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
        ),
    ]
