# Generated by Django 4.1.6 on 2023-11-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0069_alter_subject_code_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.ManyToManyField(default=list, related_name='grade_subjects', to='course.grade'),
        ),
    ]
