# Generated by Django 4.1.6 on 2023-11-13 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0070_alter_subject_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='code',
            field=models.CharField(db_index=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='num',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.TextField(blank=True, db_index=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='num',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='chapter',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, default='', max_length=50, null=True)),
                ('created', models.DateField(auto_now_add=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_query', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
