# Generated by Django 4.1.6 on 2023-11-21 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0071_alter_grade_code_alter_grade_name_alter_lesson_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, null=True)),
                ('created', models.DateField(auto_now_add=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('subject', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_subtopics', to='course.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateField(auto_now_add=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('grade', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_chapters', to='course.grade')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_chapters', to='course.subject')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_chapters', to='course.topic')),
            ],
        ),
    ]
