# Generated by Django 4.1.5 on 2023-02-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(db_index=True, default='', max_length=15, null=True)),
                ('grade', models.CharField(db_index=True, max_length=255, null=True)),
                ('age', models.SmallIntegerField(db_index=True, null=True)),
                ('gender', models.CharField(db_index=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('name_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.SmallIntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(db_index=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
