# Generated by Django 4.1.5 on 2023-02-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_tempstudent_student_age_student_gender_student_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempstudent',
            name='username',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
    ]
