"""
Django settings for edufox project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import logging
from pathlib import Path
# from decouple import config
import environ
import os
import io
import google.auth
from environ import Env
from google.cloud import secretmanager
from urllib.parse import urlparse
from google.oauth2 import service_account

from client.library import GoogleCloudSecretRepo, LocalCredentialsRepo

# logging.basicConfig(level=logging.DEBUG)

env = environ.Env(DEBUG=(bool, True), USE_CLOUD_BUILD=(bool, True))
# environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

arr = os.listdir('.')
# os.environ['USE_CLOUD_SQL_AUTH_PROXY'] = 'True'
FILE = CREDS_PATH = ''
for i in range(len(arr)):
    # if 'gha-creds' in arr[i] or 'creds.json' == arr[i]: #cloudbuild.yml
    if 'gha-creds' in arr[i]:  # ci.yml
        FILE = arr[i]
# print('FILE::', FILE)
if FILE:
    env_file = os.path.join(BASE_DIR, FILE)
    os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = env_file
    os.environ['USE_CLOUD_SQL_AUTH_PROXY'] = 'True'
    CREDS_PATH = env_file


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/


# env cloud secret setup
PROJECT_ID = "edufox-services"
# client = secretmanager.SecretManagerServiceClient()

# settings_name = os.environ.get("SETTINGS_NAME", "django_settings")
# name = f"projects/{PROJECT_ID}/secrets/{settings_name}/versions/latest"
# payload = client.access_secret_version(name=name).payload.data.decode("UTF-8")
# env.read_env(io.StringIO(payload))


repo_credentials = ''
if os.environ.get('USE_LOCAL_POSTGRESQL'):
    # use local env for environment variable
    repo_credentials = LocalCredentialsRepo()
    env, read_env = repo_credentials.getEnvironmentVariables()
    read_env()

else:
    # use google cloud secrets for environment variable
    # if os.environ.get('USE_CLOUD_SQL_AUTH_PROXY', ''):
    repo_credentials = GoogleCloudSecretRepo(
        "django_settings", PROJECT_ID)
    env, read_env, secrets_uri = repo_credentials.getEnvironmentVariables()
    read_env(secrets_uri)

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = True

SECRET_KEY = env("SECRET_KEY")
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_DEFAULT_REGION = env("AWS_DEFAULT_REGION")


# SECURITY WARNING: don't run with debug turned on in production!

# SECURITY WARNING: It's recommended that you use this when
# running in production. The URL will be known once you first deploy
# to Cloud Run. This code takes the URL and converts it to both these settings formats.
CLOUDRUN_SERVICE_URL = env("CLOUDRUN_SERVICE_URL", default=None)
ALLOWED_HOSTS = []
CSRF_TRUSTED_ORIGINS = []
PROTOCOL = ""
DOMAIN = ""
# print('CLOUDRUN_SERVICE_URL: ', CLOUDRUN_SERVICE_URL)
if CLOUDRUN_SERVICE_URL:
    # print('CLOUDRUN_SERVICE_URL: ', CLOUDRUN_SERVICE_URL)
    service_url = urlparse(CLOUDRUN_SERVICE_URL).netloc
    ALLOWED_HOSTS = [service_url, 'api-service-5wasy3cpxq-uc.a.run.app', 'localhost:3000',
                     'localhost', '127.0.0.1:3000', '127.0.0.1', '10.0.2.2', 'http://localhost:3000', "192.168.0.101"]
    CSRF_TRUSTED_ORIGINS = [CLOUDRUN_SERVICE_URL,
                            'https://api-service-5wasy3cpxq-uc.a.run.app', 'http://localhost:3000', 'http://localhost', 'http://127.0.0.1:3000', 'http://127.0.0.1', 'http://10.0.2.2']
    # SECURE_SSL_REDIRECT = True
    # SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    PROTOCOL = "https"
    DOMAIN = service_url
    os.environ['USE_CLOUD_SQL_AUTH_PROXY'] = ''

else:
    # ALLOWED_HOSTS = ["*"]
    PROTOCOL = "http"
    DOMAIN = "127.0.0.1:8000"
    ALLOWED_HOSTS = ['*', '10.0.2.2', 'localhost', '*', ".localhost",
                     "127.0.0.1", ".local", "CTOs-MacBook-Pro.local", "192.168.0.101", "192.168.0.102"]
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:8000',
        'http://192.168.0.100',
        'http://192.168.0.100:8000',
        'http://*:8000',
        'http://10.0.2.2',
        'http://192.168.0.101',
        'http://192.168.0.101:8000',
        'http://192.168.0.102:8000',
        "http://CTOs-MacBook-Pro.local",
    ]
    CORS_ORIGIN_ALLOW_ALL = True
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_ORIGIN_WHITELIST = [
        'http://192.168.0.102:8000',  # Replace with your React Native app's URL
    ]
# CORS_ALLOW_METHODS = [
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
# ]
# ALLOWED_HOSTS = ["*"]
# PROTOCOL = "http"
# DOMAIN = "127.0.0.1:8000"

# print(ALLOWED_HOSTS)

# CORS_ALLOW_ALL_ORIGINS = True
# CSRF_TRUSTED_ORIGINS = [
#     'https://edufox-api-service-5wasy3cpxq-uc.a.run.app',
#     'https://api-service-5wasy3cpxq-uc.a.run.app',
#     'http://127.0.0.1', 'https://localhost:8000',
#     'http://localhost:8000', 'https://127.0.0.1',
#  ]
# ALLOWED_HOSTS = [
#     'https://api-service-5wasy3cpxq-uc.a.run.app',
#     'api-service-5wasy3cpxq-uc.a.run.app', '127.0.0.1',
#     'localhost:8000', 'localhost',
#     'https://edufox-api-service-5wasy3cpxq-uc.a.run.app',
#     'edufox-api-service-5wasy3cpxq-uc.a.run.app',
# ]


# CORS_ORIGIN_ALLOW_ALL = True
# CORS_ALLOW_CREDENTIALS = True
# ALLOWED_HOSTS = ['10.0.2.2', 'localhost', '*', ".localhost", "127.0.0.1", ".local", "CTOs-MacBook-Pro.local", "172.20.10.2"]
# CORS_ALLOWED_ORIGINS = [
#     "http://CTOs-MacBook-Pro.local",
#     'https://api-service-5wasy3cpxq-uc.a.run.app',
#     'http://localhost:8000',
#     'https://edufox-api-service-5wasy3cpxq-uc.a.run.app',
#     'http://localhost:3000',
#     'http://172.20.10.2',
#     'http://172.20.10.2:8000'
# ]
# CORS_ORIGIN_WHITELIST = [
#     'https://api-service-5wasy3cpxq-uc.a.run.app',
#     'https://localhost:8000', 'https://127.0.0.1',
#     'http://localhost:8000', 'http://127.0.0.1',
#     'https://edufox-api-service-5wasy3cpxq-uc.a.run.app',
#     'edufox-api-service-5wasy3cpxq-uc.a.run.app',
#     'http://localhost:3000',
#     "http://CTOs-MacBook-Pro.local",
#     'http://172.20.10.2',
#     'http://172.20.10.2:8000'
# ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'student',
    'course',
    'notify',
    'api',
    'subscribe',
    'contact',
    'assess',
    'rest_framework',
    'rest_framework.authtoken',
    'djoser',
    'rest_framework_swagger',
    'django_filters',
    'client',
    'banner',
    'bleach',
    'autocomplete',
    'fileUpload',
    'form'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edufox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['student/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'staticfiles': 'django.templatetags.static',
            }
        },
    },
]


ALLOWED_HOSTS = ['*', '10.0.2.2', 'localhost', ".localhost",
                 "127.0.0.1", ".local", "CTOs-MacBook-Pro.local"]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = False
# CORS_ORIGIN_WHITELIST = [
#     '*'
# ]

WSGI_APPLICATION = 'edufox.wsgi.application'
# DB_NAME=env("DB_NAME")
# DB_PASSWORD=env("DB_PASSWORD")
# DB_HOST=env("DB_HOST")
# DB_PORT=env("DB_PORT")
# DB_ENGINE=env('DB_ENGINE')

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         DATABASE_URL: DATABASE_URL
#         # 'ENGINE': env('DB_ENGINE'),
#         # 'NAME': env('DB_NAME'),
#         # 'USER': env('DB_USER'),
#         # 'PASSWORD': env('DB_PASSWORD'),
#         # 'HOST': env('DB_HOST_TEST'),
#         # 'PORT': env('DB_PORT'),
#     }
# }
# DATABASES = {"default": env.db()}
if os.environ.get('USE_LOCAL_POSTGRESQL'):
    # print('USE_LOCAL_POSTGRESQL: ', os.environ.get('USE_LOCAL_POSTGRESQL'))
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME':  env("DB_NAME3"),
            'USER': env('DB_USER3'),
            'PASSWORD': env('DB_PASSWORD3'),
            'HOST': 'localhost',
            'PORT': 5432,
        },
        # 'dynamodb': {
        #     'ENGINE': 'django_dynamodb_backend',
        #     'AWS_ACCESS_KEY_ID': env('AWS_ACCESS_KEY_ID2'),
        #     'AWS_SECRET_ACCESS_KEY': env('AWS_SECRET_ACCESS_KEY2'),
        #     'AWS_REGION_NAME': env('AWS_DEFAULT_REGION'),
        #     # 'AWS_DYNAMODB_ENDPOINT_URL': 'your-dynamodb-endpoint-url',
        # },
    }

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME':  env("DB_NAME"),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
        }
    }

if CLOUDRUN_SERVICE_URL or env('USE_CLOUD_BUILD') and not os.environ.get('USE_LOCAL_POSTGRESQL'):
    # print('CLOUDRUN_SERVICE_URL: ', CLOUDRUN_SERVICE_URL)
    DATABASES = {"default": env.db()}

# # If the flag as been set, configure to use proxy
if os.environ.get('USE_CLOUD_SQL_AUTH_PROXY'):
    # CI.yml always enable, else github action will fail
    DATABASES["default"]["HOST"] = "cloudsql-proxy"
    # DATABASES["default"]["HOST"] = "127.0.0.1"
    ''

if os.environ.get('USE_LOCAL_POSTGRESQL'):
    DATABASES["default"]["HOST"] = "127.0.0.1"  # local

DATABASES["default"]["PORT"] = 5432

# print('DATABASES3 : ', DATABASES["default"])
# print('USE_LOCAL_POSTGRESQL : ', os.environ.get('DB_PASSWORD'))

# Define static storage via django-storages[google]
# GS_BUCKET_NAME = env("GS_BUCKET_NAME")

STATIC_URL = "/static/"

storage_params = repo_credentials.getParams()

if not os.environ.get('USE_LOCAL_POSTGRESQL'):
    GS_BUCKET_NAME = storage_params.get('GS_BUCKET_NAME', '')
    GS_PROJECT_ID = storage_params.get("GS_PROJECT_ID", '')
    DEFAULT_FILE_STORAGE = storage_params.get('DEFAULT_FILE_STORAGE', '')
    STATICFILES_STORAGE = storage_params.get('STATICFILES_STORAGE', '')
    GS_AUTO_CREATE_BUCKET = storage_params.get('GS_AUTO_CREATE_BUCKET', '')
    GS_QUERYSTRING_AUTH = storage_params.get('GS_QUERYSTRING_AUTH', '')


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],

    "DEFAULT_PERMISSION_CLASSES": [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly'
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',

    # 'DEFAULT_PAGINATION_CLASS' : 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 15,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '10/minute',
    #     'user': '50/minute'
    # }

}
CACHE_MIDDLEWARE_ANONYMOUS_ONLY = True

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        "TIMEOUT": 300,
        "OPTIONS": {"MAX_ENTRIES": 100, "CULL_FREQUENCY": 3},
    },

    'autocomplete_redis_cache': {
        'BACKEND': 'django_redis.cache.RedisCache',
        # Replace with your Redis server IP Address
        'LOCATION': 'redis://10.76.144.3:6379',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'TIMEOUT': None,  # Set the desired timeout e.g 3600
    },
}


DJOSER = {
    'SET_PASSWORD_RETRIES': 5,
    'PASSWORD_VALIDATORS': [
        {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
        {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
        {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
        {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
    ],
    "USER_ID_FIELD": "username",
    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': 'username/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': 'api/v1/auth/activate/{uid}/{token}',

    # 'SEND_ACTIVATION_EMAIL': True,
    # 'SEND_CONFIRMATION_EMAIL': True,
    'PASSWORD_RESET_CONFIRM_EMAIL_SUBJECT_TEMPLATE': 'TESTING',
    'EMAIL': {
        'activation': 'student.views.ActivationEmail',
        'confirmation': 'student.views.ConfirmationEmail',

    },
    # 'SERIALIZERS': { 'user': 'student.serializers.StudentSerializer',},
}

# AUTH_USER_MODEL = 'student.Student'

LOGIN_URL = 'api:login'
LOGOUT_URL = 'api:logout'

EMAIL_BACKEND = env('EMAIL_BACKEND')
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

# placeholder = (
#         f"SECRET_KEY=django-insecure-5xh$hw9%n$huk$mql=%r7p@dxefh9+hleb7yb$eo_6p)r*$dn^\n"
#         "GS_BUCKET_NAME=edufox-bucket\n"
#         "EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend\n"
#         "EMAIL_HOST=smtp.gmail.com\n"
#         "EMAIL_PORT=587\n"
#         "EMAIL_HOST_USER=app.edufox@gmail.com\n"
#         "EMAIL_HOST_PASSWORD=sofeipbagutmjhkc\n"
#         f"DATABASE_URL=postgres://admin:_edufox@123A@//cloudsql/edufox-services:us-central1:edufox-db-instance/edufox_db"
#     )


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC_URL = 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
