"""
Django settings for edufox project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
# from decouple import config
import environ
import os
import io
import google.auth
from google.cloud import secretmanager
from urllib.parse import urlparse
from google.oauth2 import service_account


env = environ.Env(DEBUG=(bool, True))
# environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
# SECRET_KEY = os.environ.get('SECRET_KEY')
arr = os.listdir('.')
# os.environ['USE_CLOUD_SQL_AUTH_PROXY'] = 'true'
FILE = ''
for i in range(len(arr)):
    # if 'gha-creds' in arr[i] or 'creds.json' == arr[i]: #cloudbuild.yml
    if 'gha-creds' in arr[i]: #ci.yml
        FILE = arr[i]
print('FILE::', FILE)
if FILE:
    env_file = os.path.join(BASE_DIR, FILE)
    os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = env_file
    os.environ['USE_CLOUD_SQL_AUTH_PROXY'] = 'True'


# env = environ.Env(
#     GOOGLE_APPLICATION_CREDENTIALS=(os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")),
#     # DATABASE_URL=(os.environ.get("DATABASE_URL")),
#     # GS_BUCKET_NAME=(str, os.environ.get("GS_BUCKET_NAME")),
# )
# print('GOOGLE_APPLICATION_CREDENTIALS', env('GOOGLE_APPLICATION_CREDENTIALS'))
# placeholder = (
#         f"SECRET_KEY=django-insecure-5xh$hw9%n$huk$mql=%r7p@dxefh9+hleb7yb$eo_6p)r*$dn^\n"
#         "GS_BUCKET_NAME=edufox-bucket\n"
#         f"DATABASE_URL={os.getenv('DATABASE_URL')}"
#     )
# env.read_env(io.StringIO(placeholder))

# print(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# Attempt to load the Project ID into the environment, safely failing on error.
# os.environ['DATABASE_URL'] = ''
# # os.environ['GS_BUCKET_NAME'] = ''
# # os.environ['EMAIL_BACKEND'] = ''
# # os.environ['EMAIL_HOST'] = ''
# # os.environ['EMAIL_PORT'] = ''
# # os.environ['EMAIL_HOST_USER'] = ''
# # os.environ['EMAIL_HOST_PASSWORD'] = ''
# # os.environ['DB_ENGINE'] = ''



# if os.path.isfile(env_file):
#     # Use a local secret file, if provided
#     # print('ovie')
#     env.read_env(env_file)
# # ...
# # [START_EXCLUDE]
# elif os.environ.get("GITHUB_ACTIONS", None):
#     # Create local settings if running with CI, for unit testing

#     placeholder = (
#         f"SECRET_KEY=django-insecure-5xh$hw9%n$huk$mql=%r7p@dxefh9+hleb7yb$eo_6p)r*$dn^\n"
#         "GS_BUCKET_NAME=edufox-bucket\n"
#         f"DATABASE_URL=postgres://admin:_edufox@123A@//cloudsql/edufox-services:us-central1:edufox-db-instance/edufox_db"
#     )
#     env.read_env(io.StringIO(placeholder))
# # [END_EXCLUDE]
# elif os.environ.get("GOOGLE_CLOUD_PROJECT", None):
    # Pull secrets from Secret Manager

# PROJECT_ID = os.env("GOOGLE_CLOUD_PROJECT")
# print('PROJECT_ID', PROJECT_ID)
PROJECT_ID = "edufox-services"
client = secretmanager.SecretManagerServiceClient()

settings_name = os.environ.get("SETTINGS_NAME", "django_settings")
name = f"projects/{PROJECT_ID}/secrets/{settings_name}/versions/latest"
payload = client.access_secret_version(name=name).payload.data.decode("UTF-8")
env.read_env(io.StringIO(payload))

# service_account_name = f"projects/{PROJECT_ID}/secrets/SERVICE_ACCOUNT/versions/latest"
# service_account_payload = client.access_secret_version(name=service_account_name).payload.data.decode("UTF-8")
# env.read_env(io.StringIO(service_account_payload))

# env.read_env(os.environ.get('GOOGLE_APPLICATION_CREDENTIALS'))
# else:
#     raise Exception("No local .env or GOOGLE_CLOUD_PROJECT detected. No secrets found.")


# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = True
# print('ENV_STATUS:', env.ENVIRON)

SECRET_KEY = env("SECRET_KEY")
# GOOGLE_APPLICATION_CREDENTIALS = env('GOOGLE_APPLICATION_CREDENTIALS')

# print('SECRET_KEY', GOOGLE_APPLICATION_CREDENTIALS)
# print('USE_CLOUD_SQL_AUTH_PROXY', os.environ.get("USE_CLOUD_SQL_AUTH_PROXY"))

# SECURITY WARNING: don't run with debug turned on in production!

# SECURITY WARNING: It's recommended that you use this when
# running in production. The URL will be known once you first deploy
# to Cloud Run. This code takes the URL and converts it to both these settings formats.
CLOUDRUN_SERVICE_URL = env("CLOUDRUN_SERVICE_URL", default=None)
ALLOWED_HOSTS = []
CSRF_TRUSTED_ORIGINS = []
PROTOCOL = ""
DOMAIN = ""
# print('CLOUDRUN_SERVICE_URL: ', CLOUDRUN_SERVICE_URL)
if CLOUDRUN_SERVICE_URL:
    service_url = urlparse(CLOUDRUN_SERVICE_URL).netloc
    ALLOWED_HOSTS = [service_url, 'api-service-5wasy3cpxq-uc.a.run.app', 'localhost:3000', 'localhost', '127.0.0.1:3000', '127.0.0.1', '10.0.2.2', 'http://localhost:3000']
    CSRF_TRUSTED_ORIGINS = [CLOUDRUN_SERVICE_URL, 
    'https://api-service-5wasy3cpxq-uc.a.run.app', 'http://localhost:3000', 'http://localhost', 'http://127.0.0.1:3000', 'http://127.0.0.1', 'http://10.0.2.2']
    # SECURE_SSL_REDIRECT = True
    # SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    PROTOCOL = "https"
    DOMAIN = service_url
    os.environ['USE_CLOUD_SQL_AUTH_PROXY'] = ''

else:
    # ALLOWED_HOSTS = ["*"]
    PROTOCOL = "http"
    DOMAIN = "127.0.0.1:8000"
    ALLOWED_HOSTS = ['10.0.2.2', 'localhost', '*', ".localhost", "127.0.0.1", ".local", "CTOs-MacBook-Pro.local"]
    CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://192.168.0.100',
    'http://192.168.0.100:8000',
    'http://*:8000',
    'http://10.0.2.2',
    "http://CTOs-MacBook-Pro.local",
    ]
    CORS_ORIGIN_ALLOW_ALL = False 
    CORS_ALLOW_CREDENTIALS = True 

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
# ALLOWED_HOSTS = ["*"]
# PROTOCOL = "http"
# DOMAIN = "127.0.0.1:8000"

# print(ALLOWED_HOSTS)

# CORS_ALLOW_ALL_ORIGINS = True
# CSRF_TRUSTED_ORIGINS = [
#     'https://edufox-api-service-5wasy3cpxq-uc.a.run.app',
#     'https://api-service-5wasy3cpxq-uc.a.run.app',
#     'http://127.0.0.1', 'https://localhost:8000',
#     'http://localhost:8000', 'https://127.0.0.1',
#  ]
# ALLOWED_HOSTS = [
#     'https://api-service-5wasy3cpxq-uc.a.run.app', 
#     'api-service-5wasy3cpxq-uc.a.run.app', '127.0.0.1',
#     'localhost:8000', 'localhost',
#     'https://edufox-api-service-5wasy3cpxq-uc.a.run.app',
#     'edufox-api-service-5wasy3cpxq-uc.a.run.app',
# ]

CORS_ALLOWED_ORIGINS = [
    'https://api-service-5wasy3cpxq-uc.a.run.app',
    'http://localhost:8000',
    'https://edufox-api-service-5wasy3cpxq-uc.a.run.app',
    'http://localhost:3000',
]
CORS_ORIGIN_WHITELIST = [
    'https://api-service-5wasy3cpxq-uc.a.run.app',
    'https://localhost:8000', 'https://127.0.0.1',
    'http://localhost:8000', 'http://127.0.0.1',
    'https://edufox-api-service-5wasy3cpxq-uc.a.run.app',
    'edufox-api-service-5wasy3cpxq-uc.a.run.app',
    'http://localhost:3000'
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'student',
    'course',
    'notify',
    'api',
    'subscribe',
    'assess',
    'rest_framework',
    'rest_framework.authtoken',
    'djoser',
    'rest_framework_swagger',
    'django_filters',
    'corsheaders',

    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edufox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['student/templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                    'staticfiles': 'django.templatetags.static',
                }
        },
    },
]

WSGI_APPLICATION = 'edufox.wsgi.application'
# DB_NAME=env("DB_NAME")
# DB_PASSWORD=env("DB_PASSWORD")
# DB_HOST=env("DB_HOST")
# DB_PORT=env("DB_PORT")
# DB_ENGINE=env('DB_ENGINE')

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         DATABASE_URL: DATABASE_URL
#         # 'ENGINE': env('DB_ENGINE'),
#         # 'NAME': env('DB_NAME'),
#         # 'USER': env('DB_USER'),
#         # 'PASSWORD': env('DB_PASSWORD'),
#         # 'HOST': env('DB_HOST_TEST'),
#         # 'PORT': env('DB_PORT'),
#     }
# }

if os.environ.get('USE_LOCAL_POSTGRESQL'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'edufox_db2',
            'USER': 'admin2',
            'PASSWORD': '_admin@123A',
            'HOST': 'localhost',
            'PORT': 5432,
        }
    }

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME':  env('DB_NAME'),
            'USER': env('DB_NAME'),
            'PASSWORD': env('DB_PASSWORD'),
        }
    }

if CLOUDRUN_SERVICE_URL:
    DATABASES = {"default": env.db()}


# # If the flag as been set, configure to use proxy
if os.environ.get('USE_CLOUD_SQL_AUTH_PROXY'):
    DATABASES["default"]["HOST"] = "cloudsql-proxy" #CI.yml
    # DATABASES["default"]["HOST"] = "127.0.0.1" #local
    DATABASES["default"]["PORT"] = 5432

# Define static storage via django-storages[google]
GS_BUCKET_NAME = env("GS_BUCKET_NAME")
STATIC_URL = "/static/"
DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
STATICFILES_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
# GS_DEFAULT_ACL = "publicRead"

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

REST_FRAMEWORK =  {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],

    "DEFAULT_PERMISSION_CLASSES" : [
    'rest_framework.permissions.IsAuthenticatedOrReadOnly'
   ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PAGINATION_CLASS' : 'rest_framework.pagination.PageNumberPagination',

    # 'DEFAULT_PAGINATION_CLASS' : 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE' : 10,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '10/minute',
    #     'user': '50/minute'
    # }

}

DJOSER = {
    'SET_PASSWORD_RETRIES': 5,
    'PASSWORD_VALIDATORS': [
        {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
        {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
        {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
        {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
    ],
    "USER_ID_FIELD" : "username",
    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': 'username/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': 'api/v1/auth/activate/{uid}/{token}',

    # 'SEND_ACTIVATION_EMAIL': True,
    # 'SEND_CONFIRMATION_EMAIL': True,
    'PASSWORD_RESET_CONFIRM_EMAIL_SUBJECT_TEMPLATE': 'TESTING',
    'EMAIL': {
            'activation': 'student.views.ActivationEmail',
            'confirmation': 'student.views.ConfirmationEmail',

    },
    # 'SERIALIZERS': { 'user': 'student.serializers.StudentSerializer',},
}

# AUTH_USER_MODEL = 'student.Student'

LOGIN_URL = 'api:login'
LOGOUT_URL = 'api:logout'

EMAIL_BACKEND = env('EMAIL_BACKEND')
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

# placeholder = (
#         f"SECRET_KEY=django-insecure-5xh$hw9%n$huk$mql=%r7p@dxefh9+hleb7yb$eo_6p)r*$dn^\n"
#         "GS_BUCKET_NAME=edufox-bucket\n"
#         "EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend\n"
#         "EMAIL_HOST=smtp.gmail.com\n"
#         "EMAIL_PORT=587\n"
#         "EMAIL_HOST_USER=app.edufox@gmail.com\n"
#         "EMAIL_HOST_PASSWORD=sofeipbagutmjhkc\n"
#         f"DATABASE_URL=postgres://admin:_edufox@123A@//cloudsql/edufox-services:us-central1:edufox-db-instance/edufox_db"
#     )


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
