# Generated by Django 4.1.6 on 2023-11-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactform_email_alter_contactform_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='email',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
