# Generated by Django 4.1.6 on 2023-11-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_contactform_email_alter_contactform_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
