# Generated by Django 4.1.6 on 2023-03-28 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=127, null=True)),
                ('name', models.CharField(default='', max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=100, null=True)),
                ('question', models.TextField(default='', unique=True)),
                ('options', models.JSONField(default=dict)),
                ('option1', models.TextField(default='')),
                ('option2', models.TextField(default='')),
                ('option3', models.TextField(default='')),
                ('option4', models.TextField(default='')),
                ('option5', models.TextField(default='')),
                ('option6', models.TextField(default='')),
                ('valid_options', models.JSONField(default=dict, null=True)),
                ('topic', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('lesson', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_grade', to='course.grade')),
                ('level', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='difficulty_level', to='assess.level')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_subjects', to='course.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('test', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='assess.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
