# Generated by Django 4.1.6 on 2023-05-05 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_video_grade_video_lesson_video_subject_video_topic'),
        ('assess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_tests', to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='test',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_tests', to='course.topic'),
        ),
    ]
