# Generated by Django 4.1.6 on 2023-05-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0003_alter_test_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='valid_options',
            new_name='valid_answers',
        ),
    ]
