# Generated by Django 4.1.6 on 2023-05-06 10:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0004_rename_valid_options_test_valid_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='correct_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='test',
            name='valid_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, default=[], size=None),
        ),
    ]
