# Generated by Django 4.1.6 on 2023-05-06 11:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0005_test_correct_answers_test_valid_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='correct_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='test',
            name='valid_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, default=list, size=None),
        ),
    ]
