# Generated by Django 4.1.6 on 2023-05-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0006_alter_test_correct_answers_alter_test_valid_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option5',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option6',
        ),
        migrations.RemoveField(
            model_name='test',
            name='valid_options',
        ),
        migrations.AlterField(
            model_name='test',
            name='options',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='valid_answers',
            field=models.JSONField(default=list, null=True),
        ),
    ]
