# Generated by Django 4.1.6 on 2023-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0007_remove_test_correct_answers_remove_test_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='answer',
            field=models.JSONField(default=list),
        ),
    ]
