# Generated by Django 4.1.6 on 2023-06-29 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0009_alter_assessment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='level',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='difficulty_level', to='assess.level'),
        ),
    ]
