# Generated by Django 4.1.6 on 2023-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0010_alter_test_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
