# Generated by Django 4.1.6 on 2023-03-28 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=15, null=True, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True, unique=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(db_index=True, default='', max_length=15, null=True)),
                ('age', models.SmallIntegerField(db_index=True, null=True)),
                ('gender', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, default='', null=True)),
                ('name_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='student.country')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_student_grade', to='course.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, default='', max_length=15)),
                ('age', models.SmallIntegerField(db_index=True, default=0, null=True)),
                ('gender', models.CharField(db_index=True, default='', max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, default='', null=True)),
                ('name_institution', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_grade', to='course.grade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
