# Generated by Django 4.1.6 on 2023-02-06 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(db_index=True, default='', max_length=15, null=True)),
                ('grade', models.CharField(db_index=True, max_length=255, null=True)),
                ('age', models.SmallIntegerField(db_index=True, null=True)),
                ('gender', models.CharField(db_index=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('name_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, default='', max_length=15, null=True)),
                ('grade', models.CharField(db_index=True, max_length=255, null=True)),
                ('age', models.SmallIntegerField(db_index=True, null=True)),
                ('gender', models.CharField(db_index=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('name_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
