# Generated by Django 4.1.6 on 2023-03-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
    ]
