# Generated by Django 4.1.6 on 2023-02-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempstudent',
            name='username',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
    ]
