# Generated by Django 4.1.6 on 2023-02-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_comment_grade_interactiontype_rate_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='title',
        ),
        migrations.RemoveField(
            model_name='view',
            name='interaction_type',
        ),
        migrations.AddField(
            model_name='interaction',
            name='seek_fwd',
            field=models.CharField(db_index=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='seek_prev',
            field=models.CharField(db_index=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='video_time_of_interaction',
            field=models.CharField(db_index=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='last_name',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tempstudent',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
