# Generated by Django 4.1.6 on 2023-02-23 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_tempstudent_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=15, null=True)),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tempstudent',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='student.country'),
        ),
    ]
