# Generated by Django 4.1.6 on 2023-02-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('student', '0003_rename_name_lecturer_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='type',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='video',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='test',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='video',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='video',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='video',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='video',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
        migrations.RemoveField(
            model_name='view',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_grade', to='course.grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tempstudent',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_student_grade', to='course.grade'),
        ),
        migrations.AlterField(
            model_name='tempstudent',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.DeleteModel(
            name='InteractionType',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
