# Generated by Django 4.1.6 on 2023-03-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_tempstudent_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempstudent',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
