# Generated by Django 4.1.6 on 2023-03-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_tempstudent_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
    ]
