# Generated by Django 4.1.6 on 2023-02-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_country_created_country_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, null=True, unique=True),
        ),
    ]
