# Generated by Django 4.1.6 on 2023-03-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_video_grade_video_lesson_video_subject_video_topic'),
        ('student', '0005_remove_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_grade', to='course.grade'),
        ),
    ]
