# Generated by Django 4.1.6 on 2023-03-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_country_country_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
