# Generated by Django 4.1.6 on 2023-03-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_country_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.SmallIntegerField(db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(db_index=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name_institution',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(db_index=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tempstudent',
            name='gender',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
    ]
