# Generated by Django 4.1.6 on 2023-08-12 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0015_rename_plan_id_product_plan'),
        ('student', '0009_earn_referral_student_ref_code'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='student',
        #     old_name='ref_code',
        #     new_name='referral_code',
        # ),
        migrations.AlterField(
            model_name='referral',
            name='discount',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='discount_referral', to='subscribe.discount'),
        ),
        # migrations.AlterField(
        #     model_name='referral',
        #     name='earn',
        #     field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL,
        #                             related_name='referral_earning', to='student.earn'),
        # ),
    ]
