# Generated by Django 4.1.6 on 2023-08-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_rename_ref_code_student_referral_code_and_more'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='student',
        #     old_name='referral_code',
        #     new_name='referral',
        # ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(
                blank=True, default='', max_length=255, null=True),
        ),
    ]
