# Generated by Django 4.1.6 on 2023-08-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_rename_referral_code_student_referral_and_more'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='student',
    #         name='first_name',
    #         field=models.CharField(blank=True, default='', max_length=255, null=True),
    #     ),
    #     migrations.AddField(
    #         model_name='student',
    #         name='last_name',
    #         field=models.CharField(blank=True, default='', max_length=255, null=True),
    #     ),
    # ]
