# Generated by Django 4.1.6 on 2023-08-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_first_name_student_last_name'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='student',
    #         name='first_name',
    #     ),
    #     migrations.RemoveField(
    #         model_name='student',
    #         name='last_name',
    #     ),
    # ]
