# Generated by Django 4.1.6 on 2023-08-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_earn_user_alter_referral_user'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='student',
    #         name='my_referral',
    #     ),
    # ]
