# Generated by Django 4.1.6 on 2023-08-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_remove_student_my_referral'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='student',
    #         name='my_referral',
    #     ),
    # ]
