# Generated by Django 4.1.6 on 2023-08-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_remove_student_my_referral'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='student',
    #         name='my_referral',
    #         field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
    #     ),
    # ]
