# Generated by Django 4.1.6 on 2023-09-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_student_my_referral_student_referral'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='student',
    #         name='my_referral',
    #     ),
    #     migrations.RemoveField(
    #         model_name='student',
    #         name='referral',
    #     ),
    # ]
