# Generated by Django 4.1.6 on 2023-09-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_student_my_referrals_student_referral'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='student',
    #         name='my_referrals',
    #         field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
    #     ),
    #     migrations.AddField(
    #         model_name='student',
    #         name='referrals',
    #         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_student', to='student.referral'),
    #     ),
    # ]
