# Generated by Django 4.1.6 on 2023-09-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_student_my_referrals_student_referrals'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='student',
        #     old_name='my_referrals',
        #     new_name='my_referral',
        # ),
        # migrations.RenameField(
        #     model_name='student',
        #     old_name='referrals',
        #     new_name='referral',
        # ),
    ]
