# Generated by Django 4.1.6 on 2023-09-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_student_referral'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='student',
        #     name='my_referrals',
        # ),
        # migrations.RemoveField(
        #     model_name='student',
        #     name='referral',
        # ),
        # migrations.RemoveField(
        #     model_name='student',
        #     name='referrals',
        # ),
        # migrations.AddField(
        #     model_name='student',
        #     name='my_referral',
        #     field=models.CharField(
        #         blank=True, db_index=True, default='', max_length=255, null=True),
        # ),
    ]
