# Generated by Django 4.1.6 on 2023-09-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_remove_student_my_referrals_remove_student_referral_and_more'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='student',
        #     old_name='my_referrals',
        #     new_name='my_referral',
        # ),
        # migrations.RemoveField(
        #     model_name='student',
        #     name='referrals',
        # ),
    ]
