# Generated by Django 4.1.6 on 2023-09-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_rename_my_referrals_student_my_referral_and_more'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='student',
    #         old_name='my_referrals',
    #         new_name='my_referral',
    #     ),
    #     migrations.RemoveField(
    #         model_name='student',
    #         name='referral',
    #     ),
    # ]
