# Generated by Django 4.1.6 on 2023-09-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_rename_my_referrals_student_my_referral_and_more'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='student',
    #         name='referral',
    #     ),
    # ]
