# Generated by Django 4.1.6 on 2023-09-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_remove_student_referral'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='student',
    #         old_name='my_referrals',
    #         new_name='my_referral',
    #     ),
    #     migrations.RenameField(
    #         model_name='student',
    #         old_name='referrals',
    #         new_name='referral',
    #     ),
    # ]
