# Generated by Django 4.1.6 on 2023-09-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_rename_my_referrals_student_my_referral_and_more'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='student',
    #         old_name='my_referral',
    #         new_name='my_referralsss',
    #     ),
    #     migrations.RenameField(
    #         model_name='student',
    #         old_name='referral',
    #         new_name='referralsss',
    #     ),
    # ]
