# Generated by Django 4.1.6 on 2023-09-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_rename_my_referral_student_my_referralsss_and_more'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='student',
    #         name='my_referralsss',
    #     ),
    #     migrations.RemoveField(
    #         model_name='student',
    #         name='referralsss',
    #     ),
    # ]
