# Generated by Django 4.1.6 on 2023-09-06 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_remove_student_my_referralsss_and_more'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='student',
    #         name='referral',
    #         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_student', to='student.referral'),
    #     ),
    # ]
