# Generated by Django 4.1.6 on 2023-09-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_student_my_referral'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='referral',
    #         name='earn',
    #         field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_earning', to='student.earn'),
    #     ),
    # ]
