# Generated by Django 4.1.6 on 2023-10-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_rename_referrals_student_referral_referral_earn_and_more'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='student',
    #         old_name='referral',
    #         new_name='referrals',
    #     ),
    # ]
