# Generated by Django 4.1.6 on 2023-10-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0049_referral_earn_student_my_referral'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='student',
    #         name='referrals',
    #     ),
    #     migrations.AddField(
    #         model_name='student',
    #         name='referral_code',
    #         field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_student', to='student.referral'),
    #     ),
    # ]
