# Generated by Django 4.1.6 on 2023-08-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_banner_label_banner_name_alter_banner_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='num',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
