# Generated by Django 4.1.6 on 2023-08-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_banner_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='discountPercentage',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='firstGradientColor',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='text',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
