# Generated by Django 4.1.6 on 2023-08-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_banner_description_banner_discountpercentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='secondGradientColor',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='thirdGradientColor',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
