# Generated by Django 4.1.6 on 2024-01-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_banner_secondgradientcolor_banner_thirdgradientcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
