# Generated by Django 4.1.6 on 2023-02-21 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='SMS', max_length=127)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('from_number', models.CharField(default='', max_length=15)),
                ('to_number', models.CharField(default='', max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_sent', models.DateTimeField(db_index=True, null=True)),
                ('date_updated', models.DateTimeField(db_index=True, null=True)),
                ('status', models.CharField(default='', max_length=15, null=True)),
                ('error_code', models.CharField(default='', max_length=15, null=True)),
                ('error_message', models.CharField(default='', max_length=15, null=True)),
                ('sid', models.CharField(default='', max_length=15, null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='notify.appmessage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
